---

- name: create windows cluster
  ansible.windows.win_dsc:
    resource_name: xCluster
    Name: "{{ failover_cluster_name }}"
    DomainAdministratorCredential_username: "{{ domain_admin_username }}@{{ dns_domain_name }}"
    DomainAdministratorCredential_password: "{{ domain_admin_password }}"
  register: create_windows_cluster
  failed_when: false
  when: failover_first_node

- name: configure quorum settings
  ansible.builtin.include_tasks: quorum.yml
  when:
    - failover_cluster_quorum_enabled
    - failover_first_node

- name: wait for cluster
  ansible.windows.win_dsc:
    resource_name: xWaitForCluster
    Name: "{{ failover_cluster_name }}"
    RetryIntervalSec: "{{ failover_retry_interval_sec }}"
    RetryCount: "{{ failover_retry_count }}"
  when: not failover_first_node

- name: join windows cluster
  ansible.windows.win_dsc:
    resource_name: xCluster
    Name: "{{ failover_cluster_name }}"
    DomainAdministratorCredential_username: "{{ domain_admin_username }}@{{ dns_domain_name }}"
    DomainAdministratorCredential_password: "{{ domain_admin_password }}"
  failed_when: false
  when: not failover_first_node
