---

- name: static cluster
  ansible.builtin.include_tasks: static.yml
  when: cluster_ip_address is defined

- name: dynamic cluster
  ansible.builtin.include_tasks: dynamic.yml
  when: cluster_ip_address is not defined
