---

- name: set Quorum to node and NodeAndFileShareMajority
  ansible.windows.win_dsc:
    resource_name: xClusterQuorum
    IsSingleInstance: 'Yes'
    Type: 'NodeAndFileShareMajority'
    Resource: '{{ failover_cluster_file_share_witness }}'
  failed_when: false
