---

- name: create windows cluster
  ansible.windows.win_dsc:
    resource_name: xCluster
    Name: "{{ cluster_name }}"
    StaticIPAddress: "{{ cluster_ip_address }}"
    DomainAdministratorCredential_username: "{{ domain_admin_username }}@{{ dns_domain_name }}"
    DomainAdministratorCredential_password: "{{ domain_admin_password }}"
  register: create_windows_cluster
  ignore_errors: true
  when: first_node

- include_tasks: quorom.yml
  when:
    - cluster_quorom_enabled
    - first_node

- name: wait for cluster
  ansible.windows.win_dsc:
    resource_name: xWaitForCluster
    Name: "{{ cluster_name }}"
    RetryIntervalSec: "{{ retry_interval_sec }}"
    RetryCount: "{{ retry_count }}"
  when: not first_node

- name: join windows cluster
  ansible.windows.win_dsc:
    resource_name: xCluster
    Name: "{{ cluster_name }}"
    StaticIPAddress: "{{ cluster_ip_address }}"
    DomainAdministratorCredential_username: "{{ domain_admin_username }}@{{ dns_domain_name }}"
    DomainAdministratorCredential_password: "{{ domain_admin_password }}"
  ignore_errors: true
  when: not first_node