---

- name: ensure xFailOverCluster is available
  block:
    - name: ensure required powershell module is present
      community.windows.win_psmodule:
        name: FailoverClusterDsc
        state: present
        repository: PSGallery
        allow_clobber: true
        accept_license: true
  rescue:
    - name: install latest version of PowershellGet
      ansible.windows.win_shell: |
        $ErrorActionPreference = 'Stop'
        Install-Module -Name 'PowerShellGet' -Repository 'PSGallery' -Scope 'AllUsers' -AllowClobber -Force -Confirm:$false

    - name: ensure required powershell module is present (retry)
      community.windows.win_psmodule:
        name: FailoverClusterDsc
        state: present
        repository: PSGallery
        allow_clobber: true
        accept_license: true

- name: add windows features
  ansible.windows.win_dsc:
    resource_name: WindowsFeature
    Name: "{{ item }}"
    Ensure: Present
  register: install_features
  loop: "{{ failover_common_required_features }}"

- name: reboot if needed
  ansible.windows.win_reboot:
  when: item.reboot_required
  loop: "{{ install_features.results }}"

- name: ensure registry service is running
  ansible.windows.win_dsc:
    resource_name: Service
    Name: TermService
    StartupType: Automatic
    State: Running
