---

- name: register/deregister
  block:
    - name: ensure ActiveDirectoryDsc module is available
      block:
        - name: ensure required powershell module is present
          community.windows.win_psmodule:
            name: ActiveDirectoryDsc
            state: present
      rescue:
        - name: install latest version of PowershellGet
          ansible.windows.win_shell: |
            $ErrorActionPreference = 'Stop'
            Install-Module -Name 'PowerShellGet' -Repository 'PSGallery' -Scope 'AllUsers' -AllowClobber -Force -Confirm:$false

        - name: ensure required powershell module is present (retry)
          community.windows.win_psmodule:
            name: ActiveDirectoryDsc
            state: present

    - name: register
      ansible.builtin.include_tasks: register.yml
      when: ad_computer_registration_role_action == 'register'

    - name: deregister
      ansible.builtin.include_tasks: deregister.yml
      when: ad_computer_registration_role_action == 'deregister'
  when:
    - ad_computer_registration_computer_name is defined
    - ad_computer_registration_computer_name | length
