---

- name: add computer object
  ansible.windows.win_dsc:
    resource_name: ADComputer
    ComputerName: "{{ ad_computer_registration_computer_name }}"
    Path: '{{ ad_computer_registration_join_ou_path | default("") }}'
    Ensure: Present
  when:
    - ad_computer_registration_computer_name is defined
    - ad_computer_registration_computer_name | length
