---

- name: add computer object
  block:
    - name: add computer object (dsc)
      ansible.windows.win_dsc:
        resource_name: ADComputer
        ComputerName: "{{ ad_computer_registration_computer_name }}"
        Path: '{{ ad_computer_registration_join_ou_path | default("") }}'
        Ensure: Present

  rescue:
    - name: add computer object (microsoft.ad)
      microsoft.ad.computer:
        name: '{{ ad_computer_registration_computer_name }}'
        path: '{{ ad_computer_registration_join_ou_path | default("") }}'
        enabled: true
        state: present
