---

failover_cluster_name: "{{ cluster_name | default('testcluster') }}"
# failover_cluster_ip_address: '192.168.100.20/24' # optional, if not specified dynamic ip will be used

failover_retry_interval_sec: "{{ retry_interval_sec | default(10) }}"
failover_retry_count: "{{ retry_count | default(60) }}"

failover_dns_domain_name: "{{ dns_domain_name | default('example.com') }}"

failover_cluster_file_share_witness_path: '\\Path\{{ failover_cluster_name }}'

failover_cluster_file_share_witness: '{{ cluster_file_share_witness | default(failover_cluster_file_share_witness_path) }}'
failover_cluster_quorum_enabled: "{{ cluster_quorum_enabled | default(false) }}"

failover_first_node: "{{ first_node | default(false) }}"
